version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - echo Building the package...
      - npm run build
  post_build:
    commands:
      - echo Publishing to CodeArtifact...
      - aws codeartifact login --tool npm --repository node-core-ci --domain poclocaweb
      - npm publish
artifacts:
  files:
    - 'dist/**/*'