version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Logging in to CodeArtifact...
      - aws codeartifact login --tool npm --repository node-core-ci --domain poclocaweb

  build:
    commands:
      - echo Building the project...
      - npm run build

  post_build:
    commands:
      - echo Publishing to CodeArtifact...
      - npm publish

artifacts:
  files:
    - 'dist/**/*'